radio_browser is missing from default config

May 11 18:23:48 home-assistant hass[988]: Traceback (most recent call last):
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/mg4aqk8nhxkrwz86bxihyyf16sjgzrvb-homeassistant-2022.11.4/lib/python3.10/site-packages/homeassistant/config_entries.py", line 808, in async_create_flow
May 11 18:23:48 home-assistant hass[988]:     integration.get_platform("config_flow")
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/mg4aqk8nhxkrwz86bxihyyf16sjgzrvb-homeassistant-2022.11.4/lib/python3.10/site-packages/homeassistant/loader.py", line 728, in get_platform
May 11 18:23:48 home-assistant hass[988]:     cache[full_name] = self._import_platform(platform_name)
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/mg4aqk8nhxkrwz86bxihyyf16sjgzrvb-homeassistant-2022.11.4/lib/python3.10/site-packages/homeassistant/loader.py", line 745, in _import_platform
May 11 18:23:48 home-assistant hass[988]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/fy54v80nwdy47xv312sh9j4ajjrqvfvn-python3-3.10.9/lib/python3.10/importlib/__init__.py", line 126, in import_module
May 11 18:23:48 home-assistant hass[988]:     return _bootstrap._gcd_import(name[level:], package, level)
May 11 18:23:48 home-assistant hass[988]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
May 11 18:23:48 home-assistant hass[988]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
May 11 18:23:48 home-assistant hass[988]:   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
May 11 18:23:48 home-assistant hass[988]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
May 11 18:23:48 home-assistant hass[988]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
May 11 18:23:48 home-assistant hass[988]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
May 11 18:23:48 home-assistant hass[988]:   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
May 11 18:23:48 home-assistant hass[988]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
May 11 18:23:48 home-assistant hass[988]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
May 11 18:23:48 home-assistant hass[988]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/mg4aqk8nhxkrwz86bxihyyf16sjgzrvb-homeassistant-2022.11.4/lib/python3.10/site-packages/homeassistant/components/radio_browser/__init__.py", line 4, in <module>
May 11 18:23:48 home-assistant hass[988]:     from radios import RadioBrowser, RadioBrowserError
May 11 18:23:48 home-assistant hass[988]: ModuleNotFoundError: No module named 'radios'
May 11 18:23:48 home-assistant hass[988]: During handling of the above exception, another exception occurred:
May 11 18:23:48 home-assistant hass[988]: Traceback (most recent call last):
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/2jqbayj56ja3mj5sbd6zjkpidjwg6ahm-python3.10-aiohttp-3.8.1/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
May 11 18:23:48 home-assistant hass[988]:     resp = await request_handler(request)
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/2jqbayj56ja3mj5sbd6zjkpidjwg6ahm-python3.10-aiohttp-3.8.1/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
May 11 18:23:48 home-assistant hass[988]:     resp = await handler(request)
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/2jqbayj56ja3mj5sbd6zjkpidjwg6ahm-python3.10-aiohttp-3.8.1/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
May 11 18:23:48 home-assistant hass[988]:     return await handler(request)
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/mg4aqk8nhxkrwz86bxihyyf16sjgzrvb-homeassistant-2022.11.4/lib/python3.10/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
May 11 18:23:48 home-assistant hass[988]:     return await handler(request)
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/mg4aqk8nhxkrwz86bxihyyf16sjgzrvb-homeassistant-2022.11.4/lib/python3.10/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
May 11 18:23:48 home-assistant hass[988]:     return await handler(request)
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/mg4aqk8nhxkrwz86bxihyyf16sjgzrvb-homeassistant-2022.11.4/lib/python3.10/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
May 11 18:23:48 home-assistant hass[988]:     return await handler(request)
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/mg4aqk8nhxkrwz86bxihyyf16sjgzrvb-homeassistant-2022.11.4/lib/python3.10/site-packages/homeassistant/components/http/ban.py", line 82, in ban_middleware
May 11 18:23:48 home-assistant hass[988]:     return await handler(request)
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/mg4aqk8nhxkrwz86bxihyyf16sjgzrvb-homeassistant-2022.11.4/lib/python3.10/site-packages/homeassistant/components/http/auth.py", line 236, in auth_middleware
May 11 18:23:48 home-assistant hass[988]:     return await handler(request)
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/mg4aqk8nhxkrwz86bxihyyf16sjgzrvb-homeassistant-2022.11.4/lib/python3.10/site-packages/homeassistant/components/http/view.py", line 136, in handle
May 11 18:23:48 home-assistant hass[988]:     result = await result
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/mg4aqk8nhxkrwz86bxihyyf16sjgzrvb-homeassistant-2022.11.4/lib/python3.10/site-packages/homeassistant/components/onboarding/views.py", line 208, in post
May 11 18:23:48 home-assistant hass[988]:     await asyncio.gather(
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/mg4aqk8nhxkrwz86bxihyyf16sjgzrvb-homeassistant-2022.11.4/lib/python3.10/site-packages/homeassistant/data_entry_flow.py", line 225, in async_init
May 11 18:23:48 home-assistant hass[988]:     flow, result = await task
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/mg4aqk8nhxkrwz86bxihyyf16sjgzrvb-homeassistant-2022.11.4/lib/python3.10/site-packages/homeassistant/data_entry_flow.py", line 243, in _async_init
May 11 18:23:48 home-assistant hass[988]:     flow = await self.async_create_flow(handler, context=context, data=data)
May 11 18:23:48 home-assistant hass[988]:   File "/nix/store/mg4aqk8nhxkrwz86bxihyyf16sjgzrvb-homeassistant-2022.11.4/lib/python3.10/site-packages/homeassistant/config_entries.py", line 815, in async_create_flow
May 11 18:23:48 home-assistant hass[988]:     raise data_entry_flow.UnknownHandler
May 11 18:23:48 home-assistant hass[988]: homeassistant.data_entry_flow.UnknownHandler
